### ISSUE TITLE
Type piracy warning during precompilation

### ISSUE THREAD

**Issue by nefrathenrici** [CliMA/Kinematic1D.jl#119]
From this warning, I think the `broadcastable` [function](https://github.com/CliMA/Kinematic1D.jl/blob/322416d0fd973a0cd33f874b5213162fe9a534e4/src/calibrateKiD/KiDUtils.jl#L186) should be removed.
```
┌ Kinematic1D [a8a3bb05-6cc5-4342-abf6-5cc636bd2b35]
│  WARNING: Method definition broadcastable(CloudMicrophysics.CommonTypes.RainType) in module CommonTypes at /Users/nefrathenrici/.julia/packages/CloudMicrophysics/A4yFR/src/CommonTypes.jl:77 overwritten in module Kinematic1D at /Users/nefrathenrici/clima/Kinematic1D.jl/src/calibrateKiD/KiDUtils.jl:186.
│    ** incremental compilation may be fatally broken for this module **
└  
```

**Comment by trontrytel** [comment]
Sounds good. Is it because we have [this](https://github.com/CliMA/CloudMicrophysics.jl/blob/60cfdb81bb600ee7608b0ff0f1b2f4569876fa87/src/CommonTypes.jl#L77)?

I'll open a PR once we update to CM v0.14

**Comment by trontrytel** [comment]
Thank you!
