### ISSUE TITLE
Cleanup the NetCDF output

### ISSUE THREAD

**Issue by trontrytel** [CliMA/Kinematic1D.jl#22]
- take in dictionary as input desired output variables
- initialise the NetCDF output based on the model type (?) (i.e. don't output moisture and precipitation vars for a `NoMoisture` simulation, etc)
- figure out a better folder structure for output

**Comment by edejong-caltech** [comment]
Focus just on the dictionary aspect/cleaner folder structure

**Comment by edejong-caltech** [comment]
#52
